CREATED_BY_LABEL = ("created_by.gefyra.dev", "true")
CARGO_LABEL = ("gefyra.dev/role", "cargo")
CARGO_ENDPOINT_LABEL = "cargo_endpoint.gefyra.dev"
BRIDGE_ID_LABEL = "bridge_id.gefyra.dev"
VERSION_LABEL = "version.gefyra.dev"
ACTIVE_KUBECONFIG_LABEL = "active_kubeconfig.gefyra.dev"
ACTIVE_KUBECONFIG_CONTEXT_LABEL = "active_context.gefyra.dev"
CONNECTION_NAME_LABEL = "connection_name.gefyra.dev"
CLIENT_ID_LABEL = "gefyraclient.gefyra.dev"
