[package]
name = "carrier2"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
env_logger = "0.11.6"
log = "0.4.26"
pingora = { version = "0.4.0", features = ["lb", "boringssl"] }
serde = "1.0.218"
serde_yaml = "0.9.34"
