#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  wg-quick down wg0
}

trap _term SIGTERM

mkdir -p /dev/net
if [ ! -c /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
fi

wg-quick up /etc/wireguard/wg0.conf

sleep infinity &

wait
