name: Build and test binaries whether they start

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'client/poetry.lock'

jobs:
  mac_build:
    uses: ./.github/workflows/dist-build-mac.yaml
    secrets: inherit
  
  mac_binary_test:
    needs: mac_build
    runs-on: macos-15-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get version
        working-directory: client/
        run: |
          cat pyproject.toml | grep version -m 1 | awk '{ print "APP_VERSION="substr($3, 2, length($3) -2)}' >> $GITHUB_ENV
      - uses: actions/download-artifact@v8
        with:
          name: gefyra-${{ env.APP_VERSION }}-darwin-universal
      - name: Install QEMU 9.0.2
        uses: docker/actions-toolkit/.github/actions/macos-setup-qemu@4234ae887e72533f3e37b65494dda612f2c160a4
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v5
      - name: Sanity run Gefyra
        run: |
          ls -la
          chmod u+x ./gefyra
          docker info
          ./gefyra --debug version

  windows_build:
    uses: ./.github/workflows/dist-build-windows.yaml
    secrets: inherit

  windows_binary_test:
    needs: windows_build
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Determine App Version
        working-directory: client/
        run: |
          python ..\.github\scripts\get_version.py
          echo "${{ env.PYAPP_PROJECT_VERSION }}"
      - uses: actions/download-artifact@v8
        with:
          name: gefyra-${{ env.PYAPP_PROJECT_VERSION }}-windows-x86_64
          path: gefyra
      - name: Print info
        run: |
          ls
          docker info
      - name: Sanity run Gefyra
        shell: cmd
        run: .\gefyra\gefyra.exe --debug version

  linux_build:
    uses: ./.github/workflows/dist-build-linux.yaml
    secrets: inherit
  
  linux_binary_test:
    needs: linux_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get version
        working-directory: client/
        run: |
          cat pyproject.toml | grep version -m 1 | awk '{ print "APP_VERSION="substr($3, 2, length($3) -2)}' >> $GITHUB_ENV
      - uses: actions/download-artifact@v8
        with:
          name: gefyra-${{ env.APP_VERSION }}-linux-amd64
      - name: Sanity run Gefyra
        run: |
          chmod u+x ./gefyra
          docker info
          ./gefyra --debug version
