name: Publish Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
            node-version: '22'
      - name: Test Build
        working-directory: ./gefyra-docs
        run: |
          npm i
          npm run generate
          npx gh-pages --dotfiles -d .output/public
